### ISSUE TITLE
(everforest) Outdated color palette

### ISSUE THREAD

**Issue by antoineco** [tinted-theming/base16-schemes#13]
For context: https://github.com/sainnhe/everforest/issues/40#issuecomment-1217829346

This theme was imported from a (possibly?) old upstream PR, but it has since undergone subtle changes so the color palette is slightly outdated.

I'm creating this issue as a TODO for myself and will address it within the next 3 days (unless somebody else steps in before I do).

**Comment by belak** [comment]
Thanks for submitting this, it's good to know! We'd be happy to accept a PR updating the scheme.
