### ISSUE TITLE
Place schemes in a subfolder

### ISSUE THREAD

**Issue by heygsiri** [tinted-theming/base16-schemes#3]
It currently takes a lot of scrolling to get to the README of the repo. Placing schemes in one folder (except the root) will improve organization. Plus, it can leave room for more configuration files for Makefiles, CI, and other purposes.

Once agreed on I can make a pull request.

**Comment by belak** [comment]
Thanks for bringing this up! I'd love to change this eventually so I'll keep this issue open, but at least for a while, I'd like to keep the current setup.

The change to a single scheme repo was made in [spec 0.10.0](https://github.com/base16-project/base16/commit/18e39eb0260a2ec824443f106f71bb3fa0f42949#diff-be0ce10cca751872e1a542b26e142d82435e6d8c65c7a9fdc232b0c66b6f1dde) and was just merged a few weeks ago when we made the fork. I also pushed a [commit to base16-schemes-source](https://github.com/chriskempson/base16-schemes-source/commit/08c05a7dfda7c2dfe031a17eb123554f22888a84) which allows older builders to use the new schemes repo for now, and I'd like to wait a bit longer before we make a change which breaks older builders.

**Comment by belak** [comment]
Also, for reference, here's the original PR for [spec 0.10.0](https://github.com/chriskempson/base16/pull/250) - I even listed this under "Potential Alternate Versions".

**Comment by joshgoebel** [comment]
I concur, when convenient these should move to a subfolder.

**Comment by belak** [comment]
We've just released spec 0.11.0 and are in the process of migrating to https://github.com/tinted-theming/schemes where all scheme systems are in subfolders.

This repo is being deprecated and will be archived soon, but we will leave it around to avoid breaking builders which only support 0.10.
