### ISSUE TITLE
Catppuccin variants missing from readme

### ISSUE THREAD

**Issue by clach04** [tinted-theming/base16-schemes#39]
Catppuccin (home https://github.com/catppuccin/base16) added in https://github.com/tinted-theming/base16-schemes/pull/24 is not listed in the readme.

I would open a PR to add it but I'm not clear if the variants should be listed in the readme or not. What's the policy/ expectation?

**Comment by belak** [comment]
We are in the process of archiving this repo and migrating to a new schemes repository. I've gone ahead and updated the base16 README over there in [this commit](https://github.com/tinted-theming/schemes/commit/ec83b6eef11da1cda5fbbd78e62516d2a898c01e) to include the original source of catppuccin.
