### ISSUE TITLE
Should this repo be versioned? (for legacy version builders)

### ISSUE THREAD

**Issue by joshgoebel** [tinted-theming/base16-schemes#9]
_Right now 0.9 build tools should be able to work with this repo AFAIK._  Therefore, should we create a tag/release of this repo for legacy uses? Either matching versions with the spec or perhaps it's own release numbering with the README explaining which version is compatible with which spec version?

IE, I propose:

- Release version 0.9 today as spec 0.9 compatible and note this in the README.

When we start adding new (potentially incompatible) data to the  `yml` files that would break the compatibility with older builders and we can point people back to the 0.9 point, etc.

**Comment by belak** [comment]
Yes, when we make a backwards compatible change, we'll tag the last commit which supports a given spec version with that version... maybe something like base16-0.9.1 (or just v0.9.1 if we stick with just base16 schemes in here).
